### PR TITLE
Update SBOMs for proton-bridge

### PR DESCRIPTION
**Pull request by nscuro**
As of *cyclonedx-gomod* v0.6.0, generated SBOMs include license information. I also added SBOMs for another version of *proton-bridge* to address #5.

### CODE REVIEW

**Comment by stevespringett** [comment]
Looks like the SBOMs are invalid. A license can be either a resolved SPDX license ID or an unresolved license name, but not both.

Refer to 

https://cyclonedx.org/docs/1.2/#type_licenseType

https://cyclonedx.org/use-cases/#license-compliance

**Comment by nscuro** [comment]
Thanks for pointing that out @stevespringett. I created a fix and will update this PR once GitHub Actions is working again.

**Comment by nscuro** [comment]
SBOMs have been regenerated with v0.6.1 of cyclonedx-gomod, which includes a fix for the issue.

**Comment by stevespringett** [comment]
Thanks @nscuro. Validated all four. Looks good and thanks for the PR.

**Pull request merged**
